server {
    listen 80;
    server_name gps.midominio.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name gps.midominio.com;

    ssl_certificate /etc/letsencrypt/live/gps.midominio.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/gps.midominio.com/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:5055;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
    }
}
