cliArgs:
  baseurl: "/"
  port: 3000
  logdir: "/tmp"
  logsize: "10M"
  geometry: true
  planmode: true
  router: "osrm"
  threads: 4
  explore: 5
  timeout: 300000
  limit: "1mb"
  maxlocations: 1000
  maxvehicles: 200
  override: ["c", "g", "l", "t", "x"]

routingServers:
  osrm:
    car:
      host: "osrm"
      port: "5000"
