cliArgs:
  baseurl: "/"
  port: 3000
  logdir: "/tmp"
  logsize: "10M"
  geometry: true
  planmode: true
  router: "osrm"
  path: "/usr/local/bin/"
  threads: 4
  timeout: 300000
  maxlocations: 1000
  maxvehicles: 200

routingServers:
  osrm:
    car:
      host: "osrm-mxo.railway.internal"
      port: "5000"
