doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: '16'
    charset: utf8
  orm:
    auto_generate_proxy_classes: true
    auto_mapping: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool
    dql:
      string_functions:
        JSON_TEXT: App\Doctrine\Dql\JsonToTextFunction
    filters:
      customer_tenant:
        class: App\Doctrine\CustomerTenantFilter
        enabled: false
      soft_delete:
        class: App\Doctrine\SoftDeleteFilter
        enabled: true
    mappings:
      App:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
      # Infrastructure mapping activated during entity swap (step 1.9)
      # Infrastructure:
      #   type: attribute
      #   is_bundle: false
      #   dir: '%kernel.project_dir%/src/Infrastructure'
      #   prefix: 'App\Infrastructure'
