version: '3.9'
services:
  mariadb:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  traccar:
    image: traccar/traccar:latest
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - '127.0.0.1:8082:8082'
      - '127.0.0.1:5055:5055'
    volumes:
      - ./traccar.xml:/opt/traccar/conf/traccar.xml

volumes:
  mariadb_data:
