#!/usr/bin/env bash
# render-vocabulary.sh — generate docs/knowledge/ubiquitous-language.md
# from docs/knowledge/_vocabulary.yaml.
#
# Read-only artifact for humans; YAML is source of truth. Groups entries
# by `bounded_context` for navigation. Regenerated by `make manifest`.
#
# Origin: 2026-04-29 hito 3 phase A.

set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
VOCAB_FILE="${VOCAB_FILE:-$REPO/docs/knowledge/_vocabulary.yaml}"
OUTPUT="${OUTPUT:-$REPO/docs/knowledge/ubiquitous-language.md}"

if [ ! -f "$VOCAB_FILE" ]; then
  echo "ERROR: $VOCAB_FILE not found" >&2
  exit 1
fi

# Validate YAML via awk: every entry must have non-empty canonical + definition.
INVALID=$(awk '
  /^  - canonical: / {
    if (in_entry && !has_def) print "missing definition for: " canonical
    canonical=$0; sub(/^  - canonical: /, "", canonical)
    in_entry=1; has_def=0
  }
  /^    definition: / { has_def=1 }
  END { if (in_entry && !has_def) print "missing definition for: " canonical }
' "$VOCAB_FILE")

if [ -n "$INVALID" ]; then
  echo "ERROR: invalid vocabulary YAML:" >&2
  echo "$INVALID" >&2
  exit 1
fi

# Build context → entry-blocks map. Stream awk to group entries.
# Each entry block is multi-line; we accumulate per-context arrays.
TMP_OUT=$(mktemp)
trap 'rm -f "$TMP_OUT"' EXIT

cat > "$TMP_OUT" <<EOF
# Ubiquitous Language

> **Auto-generated** from \`docs/knowledge/_vocabulary.yaml\` by
> \`scripts/render-vocabulary.sh\` (invoked from \`make manifest\`).
> **Do not edit this file directly** — edit the YAML instead.
>
> Origin: 2026-04-29 hito 3 phase A. DDD reference: Evans' Ubiquitous
> Language. Schema documented in \`_vocabulary.yaml\`.

EOF

# Pass 1: collect unique bounded_contexts (sorted).
CONTEXTS=$(awk '
  /^    bounded_context: / { sub(/^    bounded_context: /, ""); print }
' "$VOCAB_FILE" | sort -u)

# Pass 2: for each context, emit entries. Use awk to extract per-entry
# fields (canonical, definition, aliases). For brevity in the rendered
# view, show: canonical + aliases inline + definition.
for ctx in $CONTEXTS; do
  [ -z "$ctx" ] && continue
  echo "## ${ctx}" >> "$TMP_OUT"
  echo "" >> "$TMP_OUT"

  awk -v target_ctx="$ctx" '
    /^  - canonical: / {
      if (cur_ctx == target_ctx && canonical != "") emit()
      canonical=$0; sub(/^  - canonical: /, "", canonical)
      definition=""; aliases=""; cur_ctx=""; lifecycle="active"
      next
    }
    /^    definition: / {
      def=$0; sub(/^    definition: \"?/, "", def); sub(/\"$/, "", def)
      definition=def
    }
    /^    bounded_context: / {
      c=$0; sub(/^    bounded_context: /, "", c); cur_ctx=c
    }
    /^    lifecycle: / {
      l=$0; sub(/^    lifecycle: /, "", l); lifecycle=l
    }
    /^      - \{term: "/ {
      t=$0
      sub(/^      - \{term: "/, "", t)
      sub(/", lang:.*$/, "", t)
      if (aliases == "") aliases = t
      else aliases = aliases ", " t
    }
    function emit() {
      depr = (lifecycle == "deprecated") ? " *(deprecated)*" : ""
      al = (aliases != "") ? " — aliases: " aliases : ""
      printf "- **%s**%s%s\n", canonical, depr, al
      if (definition != "") printf "  %s\n", definition
      printf "\n"
    }
    END { if (cur_ctx == target_ctx && canonical != "") emit() }
  ' "$VOCAB_FILE" >> "$TMP_OUT"
done

mv "$TMP_OUT" "$OUTPUT"
trap - EXIT

ENTRY_COUNT=$(grep -c '^  - canonical: ' "$VOCAB_FILE")
echo "✓ Rendered $ENTRY_COUNT entries to $OUTPUT"
